/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegonematodo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Asus
 */
public class Laberinto extends javax.swing.JFrame {
int x,y,estado=0;
ImageIcon salud1= new ImageIcon("imagenLabe/salud1.png");
ImageIcon salud2= new ImageIcon("imagenLabe/salud2.png");
ImageIcon salud3= new ImageIcon("imagenLabe/salud3.png");
ImageIcon salud4= new ImageIcon("imagenLabe/salud4.png");
ImageIcon muerto= new ImageIcon("imagenLabe/muerto.png");
ImageIcon imagen1 = new ImageIcon("imagenLabe/gusano.png");
ImageIcon imagen2 = new ImageIcon("imagenLabe/gusano.abajo.png");
ImageIcon imagen3 = new ImageIcon("imagenLabe/gusanoarriba.png");
ImageIcon imagen4 = new ImageIcon("imagenLabe/gusanoizquierda.png");
ImageIcon imagen5 = new ImageIcon("imagenLabe/objetivo.png");
ImageIcon imagen6 = new ImageIcon("imagenLabe/pasto.png");
ImageIcon imagen7 = new ImageIcon("imagenLabe/agua.png");
ImageIcon imagen8 = new ImageIcon("imagenLabe/meta.jpg");
JLabel[][] camino;
boolean gus=false;
 public Clip clip;
    public String ruta="/sonidos/";
int [][] laberinto={{1,0,1,1,1,1,1,7,1,1,1,1,1,1,1,1,0,0,1,1},
                    {1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0},
                    {1,1,1,3,1,0,0,1,1,1,1,1,4,1,1,1,1,1,0,0},
                    {0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0},
                    {1,1,1,1,1,1,1,1,0,7,1,1,1,1,1,1,1,5,0,1},
                    {0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1},
                    {1,1,1,0,1,0,7,1,1,1,0,1,1,1,1,1,1,1,6,0},
                    {1,0,3,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0},
                    {1,0,1,1,1,1,1,1,7,1,1,1,0,1,4,1,0,0,1,2},
                    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0}};

    /**
     * Creates new form Laberinto
     */
    public Laberinto() {
        
        initComponents();
        this.setExtendedState(6);
        this.setResizable(false);
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        salud.setVisible(false);
        setTitle("¿CUÁLES SON LOS CONTAMINANTES DEL AGUA?");
        crear();
          ImageIcon img = new ImageIcon("icono/gusano2.png");
        this.setIconImage(img.getImage());
        //gusano.setBounds(x, y, 50, 50);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jlab = new javax.swing.JPanel();
        salud = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenLabe/derechavacio.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenLabe/derecha.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenLabe/abajovacio.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenLabe/abajo.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        iniciar.setText("Iniciar");
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenLabe/arribavacio.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenLabe/arriba.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenLabe/izquierdavacio.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setFocusPainted(false);
        jButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenLabe/izquierda.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jlab.setBackground(new java.awt.Color(64, 140, 255));
        jlab.setLayout(new java.awt.GridLayout(10, 20));

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton3.setText("REGRESAR");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlab, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(iniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salud, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iniciar)
                .addGap(101, 101, 101)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(236, 236, 236)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salud, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        x++;    
        if(x<20)
        {    
            if(laberinto[y][x]!=0)          
            mover(imagen1);
            else
            x--;
        }
        else
        x--;
      
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        y++;  
        if(y<10)
        {    
            if(laberinto[y][x]!=0)       
            mover(imagen2);
            else
            y--;
        }
        else
        y--;
       
     
       
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      
       y-=1;
       if(y>=0)
       {    
        if(laberinto[y][x]!=0)   
        mover(imagen3);
        else
        y++;
       }
       else
       y++;
     
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
      
        x-=1; 
        if(x>=0)
        {    
            if(laberinto[y][x]!=0)   
            mover(imagen4);
            else
            x++;
        }
        else
        x++;
     
    }//GEN-LAST:event_jButton5MouseClicked

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
         
        
        gus=true;
        x=0;
        y=0;
        
       
        
        Icon iconoEscalado =escalar(imagen1);
        camino[y][x].setIcon(iconoEscalado);
        //mover(imagen1);
       
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        iniciar.setVisible(false);
       
        salud.setIcon(salud1);
        salud.setVisible(true);
        
                
        
    }//GEN-LAST:event_iniciarMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laberinto().setVisible(true);
            }
        });
    }

    private void mover(ImageIcon imagen21) {
        jlab.removeAll();
        crear();
        //Icon iconoEscalado =escalar(imagen21);
        camino[y][x].setIcon(imagen21);
        if(laberinto[y][x]==2)
        { 
            try {
                        sonido("aplausos");
                        } catch (LineUnavailableException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        }
            JOptionPane.showMessageDialog(null, "Juego terminado  ", "Felicidades" , JOptionPane.INFORMATION_MESSAGE);
             jButton1.setVisible(false);
             jButton2.setVisible(false);
             jButton4.setVisible(false);
             jButton5.setVisible(false);
        }
        if(laberinto[y][x]==3)
         {
             try {
                        sonido("error");
                        } catch (LineUnavailableException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        }
           VentanaResiduos residuos;
           residuos= new VentanaResiduos(this,true);
           residuos.setVisible(true);
           JOptionPane.showMessageDialog(null,"Son usados en la agricultura para evitar que insectos u hongos perjudiquen los cultivos, \n" +
                                                " estos residuos llegan a contaminar las aguas subterráneas y terminan en ecosistemas \n" +
                                                " acuáticos como los de agua dulce alterando el equilibrio natural de los nutrientes\n" +
                                                " necesarios para la vegetación que allí habita" ,
                                                "Insecticidas, pesticidas y fertilizantes"  , JOptionPane.INFORMATION_MESSAGE);
           if(estado<4)
           estado++;
         }
         if(laberinto[y][x]==4)
         {
             try {
                        sonido("error");
                        } catch (LineUnavailableException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        }
           VentanaPlasticos plasticos;
           plasticos= new VentanaPlasticos(this,true);
           plasticos.setVisible(true);
           JOptionPane.showMessageDialog(null,  "Sustancias como el petróleo, la gasolina, plásticos, disolventes, detergentes, etc. \n" +
                                                "Estos compuestos han sido creados por el ser humano y presentan estructuras \n" +
                                                " moleculares complejas, por lo que los microorganismos no los pueden degradar.",
                                                "Productos químicos, industria y plástico" , JOptionPane.INFORMATION_MESSAGE);
           estado++;
           
         }
          if(laberinto[y][x]==5)
         {
             try {
                        sonido("error");
                        } catch (LineUnavailableException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        }
           VentanaQuimicos quimi;
           quimi= new VentanaQuimicos(this,true);
           quimi.setVisible(true);
           JOptionPane.showMessageDialog(null, " Disminuye el oxígeno, aumenta la presencia de metales pesados y dióxido  \n" +
                                                "de carbono lo cual al ingerirse a través del agua perjudica a la salud. ", 
                                                "Explotación minera y forestal" , JOptionPane.INFORMATION_MESSAGE);
           if(estado<4)
           estado++;
           
         }
           if(laberinto[y][x]==6)
         {
             try {
                        sonido("error");
                        } catch (LineUnavailableException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                        }
           VentanaSalud obsta;
           obsta= new VentanaSalud(this,true);
           obsta.setVisible(true);
           JOptionPane.showMessageDialog(null, "El excesivo y creciente consumo por parte del ser humano ha provocado\n" +
                                                " su aparición dentro de las aguas en medios naturales. Las sustancias \n" +
                                                "que los componen llegan al agua a través de nuestros excrementos y por medio \n" +
                                                "de la actividad ganadera y agrícola, ya que estos productos se utilizan para tratar \n" +
                                                "animales y plantas. Lo anterior llega al agua como consecuencia del uso del \n" +
                                                "retrete, desechos de fármacos en el baño etc.", "Fármacos" , 
                                                JOptionPane.INFORMATION_MESSAGE);
           if(estado<=4)
           estado++;
           
         }
            if(laberinto[y][x]==7)
         {
           VentanaSa salu;
           salu= new VentanaSa(this,true);
           salu.setVisible(true);
           if(estado>0)
           estado--;
           
         }
         if(estado==0)
             salud.setIcon(salud1);
         else if(estado==1)
             salud.setIcon(salud2);
         else if(estado==2)
             salud.setIcon(salud3);
         else if(estado==3)
             salud.setIcon(salud4);
         else if(estado==4)
         {
             salud.setIcon(muerto);
             JOptionPane.showMessageDialog(null, "Juego terminado  ", "La salud del gusano ha empeorado" , JOptionPane.INFORMATION_MESSAGE);   
             jButton1.setVisible(false);
             jButton2.setVisible(false);
             jButton4.setVisible(false);
             jButton5.setVisible(false);
        }
        //jlab.repaint();
       
    }

    private Icon escalar(ImageIcon imagen) {
         Image imgEscalada = imagen.getImage().getScaledInstance(camino[0][0].getWidth(),
                camino[0][0].getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        return iconoEscalado;
    }
 
     public void crear(){
       
     camino = new JLabel[20][32];
       for (int i=0;i<10;i++) {
           for (int j=0;j<20;j++) {
         
               camino[i][j]=new JLabel("",javax.swing.SwingConstants.CENTER);
               //camino[i][j].setText("5");
               camino[i][j].setSize(70,75);
               //camino[i][j].setVisible(false);
               //camino[i][j].setText(sopa[i][j]);
           
               if(laberinto[i][j]!=0)
               { 
                
                  if(laberinto[i][j]>2)
                  {
                   
                   camino[i][j].setIcon(imagen5);
                      
                  }
                  else if(laberinto[i][j]==2)
                  {
                       Icon iconoEscalado =escalar(imagen8);
                      camino[i][j].setIcon(iconoEscalado);
                  }
                  else
                  {
                      Icon iconoEscalado =escalar(imagen7);
                      camino[i][j].setIcon(iconoEscalado);
                  }
               }
               else
               {
               //camino[i][j].setOpaque(true);
               //camino[i][j].setBackground(Color.GREEN);
                   Icon iconoEscalado=escalar(imagen6);
                    camino[i][j].setIcon(iconoEscalado);
                   
               }
              
              // camino[i][j].setFont(new java.awt.Font("Segoe UI Symbol", 1, 20));
               //camino[i][j].setForeground(new java.awt.Color(0,5,2));
               //camino[i][j].setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
              //esto es para que se pueda ver el color de la casilla o cajonsito donde va la letra
               //camino[i][j].setBorder(new javax.swing.border.LineBorder(Color.BLACK, 1));//pone a la casiilla en borde con una linea negra
                             
                jlab.add(camino[i][j]);//coloca la pasilla en el panel Sopa_de_letra
               
       }
       
           
       }
       
   }
      public void sonido(String archivo)throws LineUnavailableException , IOException , UnsupportedAudioFileException{
     
        BufferedInputStream bis = new BufferedInputStream(getClass().getResourceAsStream(ruta + archivo + ".wav"));
        AudioInputStream ais = AudioSystem.getAudioInputStream(bis);
        Clip sonido=AudioSystem.getClip();
        sonido.open(ais);
        sonido.start();
        clip=sonido;
        
    
 } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jlab;
    private javax.swing.JLabel salud;
    // End of variables declaration//GEN-END:variables
}
