/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegonematodo;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Asus
 */
public class Menu extends javax.swing.JFrame {

//    FondoPanel fondo= new FondoPanel();
    ImageIcon imagen1 = new ImageIcon("src/imagenes/menu.jpg");
    /**
     * Creates new form Menu
     */
    public Menu() {
        
        //this.setContentPane(fondo);
        initComponents();
        ImageIcon img = new ImageIcon("src/icono/icono.jpg");
        //define el icon a tu JFrame
        this.setIconImage(img.getImage());
        this.setResizable(false);
        setTitle("MENU");

      setLocationRelativeTo(null);	
        
        
         
       // titulo.setIcon(iconoEscalado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton2 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        boton2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-blue.png"))); // NOI18N
        boton2.setText("Sopa de Letras");
        boton2.setBorder(null);
        boton2.setBorderPainted(false);
        boton2.setContentAreaFilled(false);
        boton2.setFocusPainted(false);
        boton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-red.png"))); // NOI18N
        boton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-green.png"))); // NOI18N
        boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton2MouseClicked(evt);
            }
        });

        boton1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-blue.png"))); // NOI18N
        boton1.setText("Seleccionar y Asociar");
        boton1.setBorder(null);
        boton1.setBorderPainted(false);
        boton1.setContentAreaFilled(false);
        boton1.setFocusPainted(false);
        boton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-red.png"))); // NOI18N
        boton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-green.png"))); // NOI18N
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
        });

        boton4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-blue.png"))); // NOI18N
        boton4.setText("Comparación");
        boton4.setBorder(null);
        boton4.setBorderPainted(false);
        boton4.setContentAreaFilled(false);
        boton4.setFocusPainted(false);
        boton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-red.png"))); // NOI18N
        boton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-green.png"))); // NOI18N
        boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton4MouseClicked(evt);
            }
        });

        boton9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        boton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-blue.png"))); // NOI18N
        boton9.setText("Rompecabezas");
        boton9.setBorder(null);
        boton9.setBorderPainted(false);
        boton9.setContentAreaFilled(false);
        boton9.setFocusPainted(false);
        boton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-red.png"))); // NOI18N
        boton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-green.png"))); // NOI18N
        boton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton9MouseClicked(evt);
            }
        });

        boton6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        boton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-blue.png"))); // NOI18N
        boton6.setText("Laberinto");
        boton6.setBorder(null);
        boton6.setBorderPainted(false);
        boton6.setContentAreaFilled(false);
        boton6.setFocusPainted(false);
        boton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-red.png"))); // NOI18N
        boton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-green.png"))); // NOI18N
        boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton6MouseClicked(evt);
            }
        });

        boton5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        boton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-blue.png"))); // NOI18N
        boton5.setText("Concentrese");
        boton5.setBorder(null);
        boton5.setBorderPainted(false);
        boton5.setContentAreaFilled(false);
        boton5.setFocusPainted(false);
        boton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-red.png"))); // NOI18N
        boton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-green.png"))); // NOI18N
        boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton5MouseClicked(evt);
            }
        });

        boton3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-blue.png"))); // NOI18N
        boton3.setText("Ahorcado");
        boton3.setBorder(null);
        boton3.setBorderPainted(false);
        boton3.setContentAreaFilled(false);
        boton3.setFocusPainted(false);
        boton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-red.png"))); // NOI18N
        boton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-green.png"))); // NOI18N
        boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton3MouseClicked(evt);
            }
        });

        boton7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-blue.png"))); // NOI18N
        boton7.setText("Crucigrama");
        boton7.setBorder(null);
        boton7.setBorderPainted(false);
        boton7.setContentAreaFilled(false);
        boton7.setFocusPainted(false);
        boton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-red.png"))); // NOI18N
        boton7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-green.png"))); // NOI18N
        boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton7MouseClicked(evt);
            }
        });

        boton8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        boton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-blue.png"))); // NOI18N
        boton8.setText("Ruleta de Preguntas");
        boton8.setBorder(null);
        boton8.setBorderPainted(false);
        boton8.setContentAreaFilled(false);
        boton8.setFocusPainted(false);
        boton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-red.png"))); // NOI18N
        boton8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/led-rounded-h-green.png"))); // NOI18N
        boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton8MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jtitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtitulo.setText("EFECTO DE AGUAS DE RÍOS CONTAMINADOS SOBRE LA SALUD HUMANA UTILIZANDO ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("C. elegans COMO MODELO BIOLÓGICO DE CONTAMINACIÓN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton3)
                    .addComponent(boton2)
                    .addComponent(boton9)
                    .addComponent(boton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton7)
                    .addComponent(boton5)
                    .addComponent(boton1)
                    .addComponent(boton4))
                .addGap(119, 119, 119))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(boton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton2)
                    .addComponent(boton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(boton9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(boton4)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton6)
                    .addComponent(boton5))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton3)
                    .addComponent(boton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(boton8)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseClicked
        SopaLetras sopa = new SopaLetras();
        sopa.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_boton2MouseClicked

    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
        asociarJFrame asociar=new asociarJFrame();
        asociar.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_boton1MouseClicked

    private void boton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton7MouseClicked
             CrosswordJF cruci = new CrosswordJF();
             cruci.setVisible(true);
             dispose();
    }//GEN-LAST:event_boton7MouseClicked

    private void boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseClicked
        JConcentrate concen = new JConcentrate();
        concen.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_boton5MouseClicked

    private void boton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton6MouseClicked
        Laberinto labe= new Laberinto();
        labe.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton6MouseClicked

    private void boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseClicked
        Ahorcado aho=new Ahorcado();
        aho.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton3MouseClicked

    private void boton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton9MouseClicked
       Rompecabezas rompe = new Rompecabezas();
       rompe.setVisible(true);
       dispose();
    }//GEN-LAST:event_boton9MouseClicked

    private void boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseClicked
        Comparacion compa=new Comparacion();
        compa.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton4MouseClicked

    private void boton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton8MouseClicked
       RuletaPreguntas ruleta=new RuletaPreguntas();
       ruleta.setVisible(true);
       dispose();
    }//GEN-LAST:event_boton8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jtitulo;
    // End of variables declaration//GEN-END:variables

   // class FondoPanel extends JPanel
    //{
      //  private Image imagen;
        
       // @Override
        //public void paint(Graphics g)
        //{
          //  imagen= new ImageIcon(getClass().getResource("/imagenes/menu.png")).getImage();
           // g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            //setOpaque(false);
            //super.paint(g);
        //}
    //}
}
