/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegonematodo;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseEvent;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Rompecabezas extends javax.swing.JFrame {

    JLabel[][] rompe;
    ImageIcon imagen1 = new ImageIcon("rompecabezas/uno.png");
    ImageIcon imagen2 = new ImageIcon("rompecabezas/dos.png");
    ImageIcon imagen3 = new ImageIcon("rompecabezas/tres.png");
    ImageIcon imagen4 = new ImageIcon("rompecabezas/cuatro.png");
    ImageIcon imagen5 = new ImageIcon("rompecabezas/cinco.png");
    ImageIcon imagen6 = new ImageIcon("rompecabezas/seis.png");
    ImageIcon imagen7 = new ImageIcon("rompecabezas/siete.png");
    ImageIcon imagen8 = new ImageIcon("rompecabezas/ocho.png");
    ImageIcon imagen9 = new ImageIcon("rompecabezas/nueve.png");
    ImageIcon imagen10 = new ImageIcon("rompecabezas/completo.png");
    ImageIcon[] imagen={imagen1,imagen2,imagen3,imagen4,imagen5,imagen6,imagen7,imagen8,imagen9};
    Stack < Integer > numeros = new Stack < Integer > ();
    int img1, img2,cont=0;
    int orden[]={0,0,0,0,0,0,0,0,0};
      public Clip clip;
    public String ruta="/sonidos/";
    /**
     * Creates new form Rompecabezas
     */
    public Rompecabezas() {
        initComponents();
        this.setResizable(false);
        Reiniciar.setVisible(false);
        completa.setIcon(imagen10);
        setLocationRelativeTo(null);	
        setTitle("¿CUÁL ES SU ANATOMÍA?");
          ImageIcon img = new ImageIcon("icono/gusano2.png");
        this.setIconImage(img.getImage());
        int pos;
        int nCartas = 9;
        
        for (int i = 0; i < nCartas ; i++) {
            pos = (int) Math.floor(Math.random() * nCartas );
            while (numeros.contains(pos)) {
                pos = (int) Math.floor(Math.random() * nCartas );
            }
            numeros.push(pos);
         }
        
        crear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        completa = new javax.swing.JLabel();
        Reiniciar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setPreferredSize(new java.awt.Dimension(1124, 800));
        panel.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        completa.setText(" ");

        Reiniciar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Reiniciar.setText("Reiniciar");
        Reiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReiniciarMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Reiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(completa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(completa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(Reiniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReiniciarMouseClicked
        int pos;
        int nCartas = 9;
        numeros.clear();
        for (int i = 0; i < nCartas ; i++) {
            pos = (int) Math.floor(Math.random() * nCartas );
            while (numeros.contains(pos)) {
                pos = (int) Math.floor(Math.random() * nCartas );
            }
            numeros.push(pos);
            orden[i]=(pos);
         }
        Repintar();
    }//GEN-LAST:event_ReiniciarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Menu menu= new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rompecabezas().setVisible(true);
            }
        });
    }
     public void crear(){
       int con=0;
     rompe = new JLabel[3][3];
       for (int i=0;i<3;i++) {
           for (int j=0;j<3;j++) {
               int numero=numeros.pop();
               orden[con]=numero;
               rompe[i][j]=new JLabel("",javax.swing.SwingConstants.CENTER);
               rompe[i][j].setName(""+con);
               //rompe[i][j].setText(""+con);
              // rompe[i][j].setSize(208,233);
               //camino[i][j].setVisible(false);
               //camino[i][j].setText(sopa[i][j]);
               rompe[i][j].setIcon(imagen[numero]);
               //camino[i][j].setOpaque(true);
               //camino[i][j].setBackground(Color.GREEN);
               // camino[i][j].setFont(new java.awt.Font("Segoe UI Symbol", 1, 20));
               //camino[i][j].setForeground(new java.awt.Color(0,5,2));
               //camino[i][j].setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
              //esto es para que se pueda ver el color de la casilla o cajonsito donde va la letra
               //camino[i][j].setBorder(new javax.swing.border.LineBorder(Color.BLACK, 1));//pone a la casiilla en borde con una linea negra
                rompe[i][j].addMouseListener(new java.awt.event.MouseAdapter() {//pone a la casilla a la escucha del mouse para saber cuando se esta dando clic
                    
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        
                        presioneClic(evt);//llama al metodo que debe ejecutarse cuando se da clic
                    }

                   
                });           
                panel.add(rompe[i][j]);//coloca la pasilla en el panel Sopa_de_letra
                con++;
               
       }
       
           
       }
       
   }
     private void presioneClic(MouseEvent evt) {
                       
                     evt.getComponent().setSize(230,206);
                       cont++;
                       
                       if(cont==2){
                           
                         img2=Integer.parseInt (evt.getComponent().getName());
                         cont=0;
                         
                         Repintar();
                         verificar();
                       }
                       else
                           img1=Integer.parseInt (evt.getComponent().getName());
                           
                   }
     void Repintar(){
     
         int a,con=0;
         a=orden[img1];
         
         orden[img1]=orden[img2];
         orden[img2]=a;
         
         
         for (int i=0;i<3;i++) {
           for (int j=0;j<3;j++) {
               
               rompe[i][j].setIcon(imagen[orden[con]]);
               rompe[i][j].setSize(233,208);
               con++;
               
       }
         
       }
         panel.repaint();
         Reiniciar.setVisible(false);
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reiniciar;
    private javax.swing.JLabel completa;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    private void verificar() {
    
            if(orden[0]==0)
                if(orden[1]==1)
                    if(orden[2]==2)
                        if(orden[3]==3)
                            if(orden[4]==4)
                                if(orden[5]==5)
                                    if(orden[6]==6)
                                        if(orden[7]==7)
                                            if(orden[8]==8)
                                            {
                                                 try {
                                                    sonido("aplausos");
                                                    } catch (LineUnavailableException ex) {
                                                        Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                                                    } catch (IOException ex) {
                                                        Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                                                    } catch (UnsupportedAudioFileException ex) {
                                                        Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
                                                    }
                                                JOptionPane.showMessageDialog(null, "Finalizado",  "Juego terminado", JOptionPane.INFORMATION_MESSAGE);
                                                
                                                 
                                                Reiniciar.setVisible(true);
                                            }
                                                
                                            }
    
      public void sonido(String archivo)throws LineUnavailableException , IOException , UnsupportedAudioFileException{
     
        BufferedInputStream bis = new BufferedInputStream(getClass().getResourceAsStream(ruta + archivo + ".wav"));
        AudioInputStream ais = AudioSystem.getAudioInputStream(bis);
        Clip sonido=AudioSystem.getClip();
        sonido.open(ais);
        sonido.start();
        clip=sonido;
        
    
 }
}
