/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegonematodo;

import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Asus
 */
public class RuletaPreguntas extends javax.swing.JFrame {

    /** FondoPanel fondo = new FondoPanel();
     * Creates new form RuletaPreguntas
     */
     FondoPanel fondo = new FondoPanel();
     int velocidad=100,Estudiantes=0;
     boolean oprimen=false;
     JLabel label = new JLabel();
     public Clip clip;
    public String ruta="/sonidos/";
    int n=1;
    public RuletaPreguntas() {
        
        this.setContentPane(fondo);
        initComponents();
         this.setResizable(false);
        setLocationRelativeTo(null);	
        Pruleta.setOpaque(false);
        setLocationRelativeTo(null);
        setTitle("Ruleta");
          ImageIcon img = new ImageIcon("icono/gusano2.png");
        this.setIconImage(img.getImage());
        label.setBounds(0,-10,780,780);
        Pruleta.setBounds(0,-10,780,780);
        this.getContentPane().add(Pruleta); 
        String fondo1="imagenesRuleta/p1.png";
        ImageIcon imagen1 = new ImageIcon(fondo1);
        label.setIcon(imagen1); 
        Pruleta.add(label);
        setTitle("REPASEMOS JUNTOS");
        this.setVisible(true); 
        this.setLocation(300,10);
        
        
        Thread hilo = new Thread()
       {
           public void run()
           {
                for(;;)
               {
                  for(n=1;n<=12;n++)
                    { 
                     imprimir("imagenesRuleta/p"+n+".png");
                     
                     //if(oprimen)
                     //TSeleccion.setText(lista[n][1]);
                    
                        for(int l=0;l<=40;l++)
                         {
                          try{
                              sleep(velocidad);

                             }
                          catch(Exception e){}
        
                          }                  
                    } 
               }
           }
       };
       hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pruleta = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PruletaLayout = new javax.swing.GroupLayout(Pruleta);
        Pruleta.setLayout(PruletaLayout);
        PruletaLayout.setHorizontalGroup(
            PruletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        PruletaLayout.setVerticalGroup(
            PruletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        jPanel1.setFocusable(false);
        jPanel1.setOpaque(false);

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton1.setText("INICIAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton3.setText("DETENER");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Pruleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pruleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        velocidad=1;
        
        try {
            sonido("ruleta");
        } catch (LineUnavailableException ex) {
            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(RuletaPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        clip.stop();
        velocidad=1000;  
        JFrame mensaje = new JFrame();
        if(n==1)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "¿Qué elementos contaminantes son producto de la industria minera? ");

            JOptionPane.showMessageDialog(mensaje, "La respuesta es: Metales pesados ");
            
        }
        else if(n==2)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "Mencione dos semejanzas entre C. elegans y el ser humano");

            JOptionPane.showMessageDialog(mensaje, "La respuesta es: Ambos tienen sistema nervioso y digestivo ");
        }
        else if(n==3)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "¿Cuáles son los tres colores de bolsa para la adecuada separación de residuos\n" +
                                "en Colombia?");

            JOptionPane.showMessageDialog(mensaje, "La respuesta es: verde negro y blanco ");
        }
        else if(n==4)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "El ciclo de vida del nematodo con que empieza");

            JOptionPane.showMessageDialog(mensaje, "La respuesta es: Con el huevo ");
        }
        else if(n==5)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "¿Con qué es alimentado el nematodo en el laboratorio?");

            JOptionPane.showMessageDialog(mensaje, "La respuesta es: Con una bacteria ");
        }
        else if(n==6)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "¿Qué elemento es utilizado para ver el nematodo en el laboratorio?");

            JOptionPane.showMessageDialog(mensaje, "La respuesta es:  Estereoscópio ");
        }
        else if(n==7)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "¿De cuáles desechos provienen la mayor cantidad de microorganismos\n" +
                                "patógenos?");

            JOptionPane.showMessageDialog(mensaje, "La respuesta es: Residuos fecales ");
        }
        else if(n==8)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "¿Mencione dos enfermedades causadas por el agua contaminada" );

            JOptionPane.showMessageDialog(mensaje, "La respuesta es: Disentería y hepatitis A ");
        }
        else if(n==9)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "¿Cómo se llaman los nematodos que son modificadas genéticamente para\n" +
            "diversos estudios?");

            JOptionPane.showMessageDialog(mensaje, "La respuesta es: Cepas trasgenicas ");
        }
        else if(n==10)
        {
            
            String getMessage = JOptionPane.showInputDialog(mensaje, "¿En qué etapa del ciclo de vida el nematodo alcanza su máximo tamaño? ");

            JOptionPane.showMessageDialog(mensaje, "La respuesta es:  L4 adulto  ");
        }
        else if(n==11)
        {
            
            JOptionPane.showMessageDialog(mensaje, "Vuelve a Girar");

            
        }  
        else if(n==12)
        {
            
            JOptionPane.showMessageDialog(mensaje, "Vuelve a Girar");

            
        }  
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RuletaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RuletaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RuletaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RuletaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RuletaPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pruleta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen= new ImageIcon(getClass().getResource("/imagenes/ruleta2.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

void imprimir(String imagenI)
    {
        this.getContentPane().add(Pruleta); 
        ImageIcon imagen1 = new ImageIcon(imagenI);
        label.setIcon(imagen1); 
        
        Pruleta.add(label);
        
    }
public void sonido(String archivo)throws LineUnavailableException , IOException , UnsupportedAudioFileException{
     
        BufferedInputStream bis = new BufferedInputStream(getClass().getResourceAsStream(ruta + archivo + ".wav"));
        AudioInputStream ais = AudioSystem.getAudioInputStream(bis);
        Clip sonido=AudioSystem.getClip();
        sonido.open(ais);
        sonido.start();
        clip=sonido;
        
    
 }
}
